Add missing QVector include
Summary:
My build was failing with
```
In file included from /home/nico/kde/src/ark/kerfuffle/pluginmanager.cpp:28:
/home/nico/kde/src/ark/kerfuffle/pluginmanager.h:138:22: error: field ‘m_plugins’ has incomplete type ‘QVector<Kerfuffle::Plugin*>’
     QVector<Plugin*> m_plugins;
                      ^~~~~~~~~
In file included from /usr/include/qt/QtCore/qglobal.h:1204,
                 from /usr/include/qt/QtCore/qnamespace.h:43,
                 from /usr/include/qt/QtCore/qobjectdefs.h:48,
                 from /usr/include/qt/QtCore/qobject.h:46,
                 from /usr/include/qt/QtCore/QObject:1,
                 from /home/nico/kde/src/ark/kerfuffle/plugin.h:33,
                 from /home/nico/kde/src/ark/kerfuffle/pluginmanager.h:31,
                 from /home/nico/kde/src/ark/kerfuffle/pluginmanager.cpp:28
```

Test Plan: Builds. Can open a file

Reviewers: #ark, elvisangelaccio

Reviewed By: #ark, elvisangelaccio

Subscribers: kde-utils-devel, #ark

Tags: #ark

Differential Revision: https://phabricator.kde.org/D22461